export default{
    authenticated:false,
    posts:[],
    search:'',

    userEmail:'',
    userType:'',
    userDbf:'',
    userFirstName:'',
    userSecondName:'',
    userShelterName:'',
    userGender:'',
    userOibSsn:'',
    userLocation:'',
    userPicture:'',

    postImageData:null,
    postImageUrl:'',
    description:'',
    animal:'',
    animals:['Dog','Cat','Other'],
    name:'',
    gender:'',
    genders:['Male','Female'],
    age:'',
    ages:['Puppy','Adult','Senior'],
    location:'',
    link:'',
    time:''
}